$(document).ready(function() {alert("be prepared to do some organizing. we are going to be talking about the chronological filing system. if you already know what it is, then that's great! if not, read the information at the top of this page and then you should the idea :) hit the all done button when you're done!!"); })

$(document).ready(function() {$("#01").draggable();})
$(document).ready(function() {$("#02").draggable();})
$(document).ready(function() {$("#03").draggable();})
$(document).ready(function() {$("#04").draggable();})
$(document).ready(function() {$("#05").draggable();})
$(document).ready(function() {$("#06").draggable();})
$(document).ready(function() {$("#07").draggable();})
$(document).ready(function() {$("#08").draggable();})
$(document).ready(function() {$("#09").draggable();})
$(document).ready(function() {$("#10").draggable();})
$(document).ready(function() {$("#11").draggable();})
$(document).ready(function() {$("#12").draggable();})
$(document).ready(function() {$("#13").draggable();})
$(document).ready(function() {$("#14").draggable();})
$(document).ready(function() {$("#15").draggable();})
$(document).ready(function() {$("#16").draggable();})
$(document).ready(function() {$("#17").draggable();})